apiVersion: v1
kind: Service

metadata:
  name: clusterip
  labels:
    name: britishtelecom
    environment: dev

spec:
  selector:
    project: bhp
    version: "6.1"
    environment: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Pod

metadata:
  name: backend
  labels:
    project: bhp
    version: "6.1"
    environment: prod

spec:
  containers:
  - name: nginx
    image: nginx