kind: Service
apiVersion: v1

metadata:
  name: nodeport
  labels:
    project: britishtelecom
    environment: dev

spec:
  type: NodePort
  selector:
    version: "6.3"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30150

---
kind: Pod
apiVersion: v1

metadata:
  name: nodeportpod
  labels:
    project: bhp
    version: "6.3"
    environment: prod

spec:
  containers:
  - name: nginx
    image: nginx
