kind: Service
apiVersion: v1

metadata:
  name: loadbalancer
  labels:
    name: americanbank
    project: platformmaintainance

spec:
  type: LoadBalancer
  selector:
    empid: "13272805"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000

---
kind: Pod
apiVersion: v1

metadata:
  name: loadbalancerpod
  labels:
    name: bhp
    version: "6.44"
    empid: "13272805"

spec:
  containers:
  - name: nginx
    image: nginx
