apiVersion: v1
kind: Service

metadata:
  name: service

spec:
  selector:
    project: bhp
    environment: prod-prod
    name: Expense
  ports:
  - protocol: TCP
    port: 80
    targetport: 80

---

apiVersion: v1
kind: Pod

metadata:
  name: servicepod
  labels:
    project: bhp
    environment: prod-prod
    name: Expense

spec:
  containers:
    - name: nginx
      image: nginx

