apiVersion: v1
kind: Service

metadata:
  name: loadbalancerservice

spec:
  type: LoadBalancer
  selector:
    name: bhp
    environment: ent-ent
    project: jenkins
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30951


---
apiVersion: v1
kind: Pod

metadata:
  name: loadbalancerpod
  labels:
    name: bhp
    environment: ent-ent
    project: jenkins

spec:
  containers:
  - name: nginx
    image: nginx
