apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginxdeploment
  labels:
    project: bhp
    environment: dev
    service: telecom

spec:
   replicas: 3
   selector:
    matchLabels:
      project: bhp
      environment: dev
      service: telecom

   template:
    metadata:
      name: deployment1
      labels:
        project: bhp
        environment: dev
        service: telecom
    spec:
      containers:
      - name: nginx
        image: saikirangoka/app:1.0.0

---

apiVersion: v1
kind: Service

metadata:
  name: service1
  labels:
    name: bhp

spec:
  type: LoadBalancer
  selector:
    project: bhp
    environment: dev
    service: telecom
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30952