kind: Pod
apiVersion: v1

metadata:
  name: annotations
  annotations:
    buildURL: "https://learn.joindevops.com/learn/home/devsecops-with-aws-82S/section/601262/lesson/3712916?"

spec:
  containers:
  - name: nginx
    image: nginx