kind: Pod
apiVersion: v1

metadata:
  name: multicontainers
  labels:
    name: Elasticsearch, Logstash, and Kibana

spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9
      command: [ "sleep", "1000"]