apiVersion: v1
kind: Pod

metadata:
  name: multicontainers
  namespace: expense
  labels:
    project: bhp
    environment: prod

spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: [ "sleep", "1000"]