apiVersion: v1
kind: Pod

metadata:
  name: resources
  labels:
   project: bt
   environment: prod

spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "68Mi"
      limits:
        cpu: "150m"
        memory: "128Mi"